package com.example.merlinproject.ui.navigation


object SplashScreen{
    const val SPLASH_SCREEN = "SPLASH_SCREEN"
}

object RoutesLoginAndRegister {
    const val WELCOME_SCREEN_NAVIGATION_ROUTE_NAME = "WELCOME_SCREEN"
    const val USER_REGISTER = "REGISTER_SCREEN"
    const val USER_LOGIN = "LOGIN_SCREEN"
    const val USER_SIGNUP = "LOGIN_SIGNUP"
}

object RoutesNavigationDrawer {
    const val SPLASH_SCREEN_ROUTE_NAME= "SPLASH_SCREEN"
    const val BACHELORS_SCREEN_ROUTE_NAME= "BACHELORS_SCREEN"
    const val ONBOARDING_NAVIGATION_ROUTE_NAME = "ONBOARDING_SCREEN"
    const val LOGIN_NAVIGATION_ROUTE_NAME = "LOGIN_SCREEN"
    const val REGISTER_NAVIGATION_ROUTE_NAME = "REGISTER_SCREEN"
    const val FORGET_PASSWORD_NAVIGATION_ROUTE_NAME = "FORGET_PASSWORD_SCREEN"
    const val HOME_NAVIGATION_ROUTE_NAME = "HOME_SCREEN"
    const val AGENDA_NAVIGATION_ROUTE_NAME = "AGENDA_SCREEN"
    const val CALENDAR_NAVIGATION_ROUTE_NAME = "CALENDAR_SCREEN"
    const val USER_NAVIGATION_ROUTE_NAME = "USER_SCREEN"
    const val TEACHER_NAVIGATION_ROUTE_NAME = "TEACHER_SCREEN"
    const val RATING_NAVIGATION_ROUTE_NAME = "RATING_SCREEN"
    const val SETTINGS_NAVIGATION_ROUTE_NAME = "SETTINGS_SCREEN"
    const val CURSES_NAVIGATION_ROUTE_NAME = "CURSES_SCREEN"
    const val PROFESSION_NAVIGATION_ROUTE_NAME = "PROFESSION_SCREEN"
    const val TERMS_AND_CONDITIONS_NAVIGATION_ROUTE_NAME = "TERMS_AND_CONDITIONS_SCREEN"
    const val HELP_AND_QUESTION_NAVIGATION_ROUTE_NAME = "HELP_AND_QUESTION_SCREEN"
}
